"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# === CHANGED: added os and load_dotenv imports ===
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# === CHANGED: load the .env file so os.environ.get() below can read it ===
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# === CHANGED: SECRET_KEY now comes from .env instead of hardcoded ===
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-fallback-for-local-only")

# === CHANGED: DEBUG now comes from .env instead of hardcoded ===
DEBUG = os.environ.get("DEBUG", "True") == "True"

# === CHANGED: ALLOWED_HOSTS now comes from .env instead of hardcoded ===
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "rest_framework",
    # Ships with djangorestframework-simplejwt. Needed so BLACKLIST_AFTER_ROTATION
    # (see SIMPLE_JWT below) has somewhere to actually store blacklisted tokens —
    # without this app registered, "blacklist after rotation" would silently do
    # nothing.
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "articles",
   "users.apps.UsersConfig",

    # registration: the account-creation flow (age/COPPA gate, optional
    # email + password, email verification, JWT issuance on signup). Kept
    # separate from `users` on purpose — `users` owns the ongoing shape of
    # an account (UserProfile), this app owns the one-time act of CREATING
    # one, which has a very different set of concerns (throttling,
    # unauthenticated endpoints, token generation). See registration/README
    # docstrings for the full reasoning.
    "registration.apps.RegistrationConfig",

    # accounts: existed as an empty stub before, wasn't even registered
    # here. Now houses the admin-account safety rules (see
    # accounts/admin.py + accounts/signals.py) — "an admin can't delete
    # their own account" (dashboard) and "the system can never be left
    # with zero superadmins" (DB-level, via a signal).
    "accounts.apps.AccountsConfig",

    # legal_docs: CRUD for Terms & Conditions / Privacy Policy content
    # (separate versions for guest vs registered users), managed through
    # the Django admin and served to the mobile app via /api/legal-documents/.
    "legal_docs.apps.LegalDocsConfig",
]

MIDDLEWARE = [
       "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
     "http://localhost:8081",
    "http://localhost:19006",
    "http://127.0.0.1:8081",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # Scoped throttle for the registration endpoint specifically — it's
    # unauthenticated by nature (nobody has an account yet) and issues real
    # JWTs, so it needs its own abuse limit independent of general API
    # traffic. See registration/views.py for where the scope is applied.
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "register": "10/hour",
        "email-verification-resend": "5/hour",
    },
}

from datetime import timedelta  # noqa: E402 (kept near SIMPLE_JWT for locality)

SIMPLE_JWT = {
    # Short-lived on purpose — if one leaks (e.g. a compromised device's
    # memory dump), the exposure window is small.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # Deliberately long (30 days, not the more common 7) — this is a
    # period-tracking app opened sporadically across a month, and an
    # active user's refresh keeps extending this anyway (see below), so
    # this mostly only matters for someone who genuinely goes quiet.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    # Every refresh issues a NEW refresh token and immediately invalidates
    # the old one — a stolen old refresh token becomes useless the moment
    # the legitimate device refreshes again.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    # An active user's session effectively never expires (each refresh
    # resets the 30-day clock) — only someone who stops using the app
    # entirely for 30 days actually gets logged out.
    "UPDATE_LAST_LOGIN": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# --- Email (for the account-verification link) ---
# Console backend for now: verification emails print straight to this
# terminal instead of actually sending anywhere — zero setup needed for
# local dev. Swap EMAIL_BACKEND (via .env) for a real SMTP/API-based
# provider (SendGrid, Mailgun, SES, Gmail SMTP...) when there's an actual
# provider to point at; nothing else in the codebase needs to change,
# since everything sends via Django's send_mail(), not a hardcoded backend.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@syncate.app")

# Used to build the verification link inside the email (e.g.
# "http://192.168.1.71:8000/verify-email/<token>/") — needs to be
# reachable by whatever device opens the email, so on a phone this has to
# be your machine's LAN IP, not 127.0.0.1. Mirrors the same LAN-IP problem
# solved on the mobile side by getApiBaseUrl.ts.
BACKEND_PUBLIC_URL = os.environ.get("BACKEND_PUBLIC_URL", "http://127.0.0.1:8000")

# === CHANGED: all 5 DB values now come from .env instead of hardcoded ===
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "syncate_db"),
        "USER": os.environ.get("DB_USER", "postgres"),
        "PASSWORD": os.environ.get("DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("DB_HOST", "localhost"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'