# Generated by Django 4.2.7 on 2026-07-21 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_contenttype_educationalcontent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationalcontent',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': 'Educational Content', 'verbose_name_plural': 'Educational Content'},
        ),
        migrations.RemoveField(
            model_name='educationalcontent',
            name='is_featured',
        ),
    ]
