# Generated by Django 4.2.7 on 2026-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tracking_mode',
            field=models.CharField(blank=True, choices=[('period', 'Period Tracking'), ('pregnancy', 'Pregnancy Tracking')], default='', max_length=20),
        ),
    ]
