# Generated by Django 4.2.7 on 2026-07-22 20:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legal_docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='LegalDocumentAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('guest_terms', 'Guest — Terms & Conditions'), ('guest_privacy', 'Guest — Privacy Policy'), ('registered_terms', 'Registered User — Terms & Conditions'), ('registered_privacy', 'Registered User — Privacy Policy')], max_length=32)),
                ('version', models.CharField(help_text='Snapshot of the version that was active at the moment of acceptance — never updated retroactively.', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_version_format', message='Version must be major.minor only, e.g. "1.0" or "2.3" — no patch numbers, no "v" prefix, no suffixes.', regex='^\\d+\\.\\d+$')])),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_document_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Document Acceptance',
                'verbose_name_plural': 'Legal Document Acceptances',
            },
        ),
        migrations.AddConstraint(
            model_name='legaldocumentacceptance',
            constraint=models.UniqueConstraint(fields=('user', 'doc_type'), name='unique_acceptance_per_user_per_doctype'),
        ),
    ]
