# Generated by Django 4.2.7 on 2026-07-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_tracking_mode'),
        ('users', '0003_unique_email_constraint'),
    ]

    operations = [
    ]
