# Generated by Django 4.2.7 on 2026-07-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_20260723_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Collected during registration for the age check. Stored as a date so the calculated age never becomes stale.', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. Deleted accounts remain in the database but are deactivated and prevented from authenticating.'),
        ),
    ]
