# Generated by Django 4.2.7 on 2026-08-27 07:37

from django.db import migrations, models
import django.utils.timezone


def backfill_registered_date(apps, schema_editor):
    UserProfile = apps.get_model('users', 'UserProfile')
    for profile in UserProfile.objects.select_related('user').iterator():
        profile.registered_date = profile.user.date_joined
        profile.save(update_fields=['registered_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this profile can authenticate and use registered features.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_date',
            field=models.DateTimeField(editable=False, help_text='Date and time this user profile was registered.', null=True),
        ),
        migrations.RunPython(
            backfill_registered_date,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='registered_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time this user profile was registered.'),
        ),
    ]
