# Generated by Django 4.2.7 on 2026-09-05 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_partner', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_relationship', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Partner',
                'verbose_name_plural': 'User Partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
