# Generated by Django 4.2.7 on 2026-08-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userprofile_is_active_userprofile_registered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='deletion_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
