# Generated by Django 4.2.7 on 2026-09-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userpartner'),
        ('users', '0007_userprofile_deletion_due_at_and_more'),
    ]

    operations = [
    ]
