# Generated by Django 4.2.7 on 2026-07-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('content_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Type',
                'verbose_name_plural': 'Content Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('content_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='educational_content/%Y/%m/')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Educational Content',
                'verbose_name_plural': 'Educational Content',
                'ordering': ['-is_featured', '-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationalContentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_type_links', to='articles.educationalcontent')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_links', to='articles.contenttype')),
            ],
            options={
                'verbose_name': 'Educational Content Type',
                'verbose_name_plural': 'Educational Content Types',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='content_types',
            field=models.ManyToManyField(related_name='educational_contents', through='articles.EducationalContentType', to='articles.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='educationalcontenttype',
            constraint=models.UniqueConstraint(fields=('content', 'content_type'), name='unique_educational_content_type'),
        ),
    ]
