# Generated by Django 4.2.7 on 2026-07-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_educationalcontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalcontent',
            name='phase',
            field=models.CharField(blank=True, choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='educationalcontent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('is_published', True)), fields=('phase',), name='one_published_article_per_phase'),
        ),
    ]
