# Generated by Django 4.2.7 on 2026-07-23 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_start_date', models.DateField(blank=True, null=True)),
                ('last_period_status', models.CharField(choices=[('not_provided', 'Not provided'), ('known', 'Known'), ('unknown', 'Unknown')], default='not_provided', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle Profile',
                'verbose_name_plural': 'Cycle Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
